import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {deriveSessionBrief as brief,renderBusinessDashboardV1Html} from '../business-dashboard-v1-view.js';
test('refresh reliability, incremental merge and freshness isolation', async () => {
const symbol='NIFTY',expiry='2026-10-13',key='NIFTY|2026-10-13|24000|CE';
const prior={market:[{symbol,minute_bucket:'2026-10-05T09:55:00Z',spot_ltp:24000,spot_high:24100,spot_low:23900,india_vix:12}],options:[{symbol,expiry,strike:24000,option_type:'CE',minute_bucket:'2026-10-05T09:55:00Z',ltp:100,oi:1000,day_high:120,day_low:80}],chain:[{symbol,expiry,minute_bucket:'2026-10-05T09:55:00Z',full_chain_oi_pcr:1.1,call_wall_strike:24200,put_wall_strike:23900}]};
const current={market:[{symbol,minute_bucket:'2026-10-06T03:45:00Z',spot_ltp:24050,spot_open:24050,spot_prev_close:24000,future_ltp:24100},{symbol,minute_bucket:'2026-10-06T03:48:00Z',spot_ltp:24060,spot_open:24050,spot_prev_close:24000,future_ltp:24110}],options:[{...prior.options[0],minute_bucket:'2026-10-06T03:48:00Z',ltp:110}],chain:[{...prior.chain[0],minute_bucket:'2026-10-06T03:48:00Z',full_chain_oi_pcr:1.2}]};
const b=brief(current,prior,[prior],symbol,expiry,key,'2026-10-06');assert.equal(b.pre.spot,24000);assert.equal(b.pre.premium,100);assert.equal(b.after.spot,24060);assert(Math.abs(b.after.gapPct-(24050/24000-1)*100)<1e-9);assert.equal(b.after.first15.count,2);assert.equal(b.after.sourceSpan,0);assert.equal(b.after.indexAgreement,'Same direction');assert.equal(b.pre.memory.length,1);
const newer=structuredClone(current);newer.market[1].spot_ltp=99999;assert.deepEqual(brief(newer,prior,[prior],symbol,expiry,key,'2026-10-06').pre,b.pre,'no after-open leakage into premarket');assert.equal(brief(current,current,[],symbol,expiry,key,'2026-10-06').pre.spot,null,'same-day rows not prior-day references');assert.equal(brief(current,{},[],symbol,'other',key,'2026-10-06').after.pcr,null);
const html=renderBusinessDashboardV1Html({}),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]),nodes=new Map();
class El{constructor(id){this.id=id;this.value='';this.innerHTML='';this.textContent='';this.dataset={};this.attributes={};this.selectedOptions=[];}setAttribute(k,v){this.attributes[k]=v;}focus(){}click(){this.onclick?.({target:this});}insertAdjacentHTML(_,s){this.innerHTML+=s;}}
ids.forEach(id=>nodes.set(id,new El(id)));nodes.set('header-nav',new El('header-nav'));for(const [id,val]of Object.entries({'detail-symbol':'NIFTY','date':'2026-10-06','baseline':'','from':'09:15','to':'15:30','summary-mode':'after','pcr-basis':'Intraday','oi-basis':'Intraday','oi-direction':'all','ladder-filter':'all','measure':'ltp','event-basis':'Intraday','event-filter':'remarkable'}))nodes.get(id).value=val;
let mode='success',calls=[];const response=(status,body)=>({status,ok:status>=200&&status<300,json:async()=>body});
const sandbox={console,Date,Map,Set,Math,Number,String,Array,Object,JSON,URL,Blob,AbortController,setTimeout:(fn,ms)=>ms===400?setTimeout(fn,0):setTimeout(fn,ms),clearTimeout,setInterval:()=>{},window:{addEventListener:()=>{}},document:{addEventListener:()=>{},getElementById:id=>nodes.get(id),querySelector:()=>nodes.get('header-nav'),hidden:false},fetch:async url=>{calls.push(url);if(url==='/auth')return response(401,{});if(url==='/transient')return response(calls.filter(x=>x===url).length===1?503:200,{ok:true});const u=new URL(url,'https://example.test'),s=u.searchParams.get('symbol');if(mode==='all-fail'||mode==='nifty-fail'&&s==='NIFTY')return response(503,{error:'TEMPORARY'});return response(200,{ok:true,market:[{symbol:s,minute_bucket:u.searchParams.get('date')+'T09:55:00Z',spot_ltp:24000}],chain:[],options:[]});}};
vm.createContext(sandbox);const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);vm.runInContext(scripts[0],sandbox);
const body=scripts[1];const start=body.indexOf("selectDashboardTab('observations');\nget('Recorded dates'");assert(start>0);vm.runInContext(body.slice(0,start)+"globalThis.__test={renderAllIndexGraphs,refreshQuoteSnapshots,selectDashboardTab,renderSourceHealth,restoreRefreshPreference,rememberRefreshPreference,load,get,getReplay,replayWindows,mergeReplayParts,replayFreshness,loadMemory,setRecordedDates:dates=>{recordedDates=dates},getMemory:()=>memory,getState:()=>({data,raw,loadedScope,indexLoadState,busy,memoryVersion})};})();",sandbox);
assert.deepEqual(JSON.parse(JSON.stringify(sandbox.__test.replayWindows('09:15','15:30'))), [['09:15','10:15'],['10:15','11:15'],['11:15','12:15'],['12:15','13:15'],['13:15','14:15'],['14:15','15:15'],['15:15','15:30']]);
const merged=sandbox.__test.mergeReplayParts([{market:{columns:['minute_bucket','spot_ltp'],rows:[['2026-10-06T03:45:00Z',24000]]},options:{columns:[],rows:[]},chain:{columns:[],rows:[]},canonical:{columns:[],rows:[]}},{market:{columns:[],rows:[]},options:{columns:[],rows:[]},chain:{columns:[],rows:[]},canonical:{columns:[],rows:[]}}],{});assert.equal(merged.market.rows.length,1);assert.equal(merged.counts.market,1);
await sandbox.__test.load();let state=sandbox.__test.getState();assert.equal(Object.keys(state.data).length,3);assert.equal(state.indexLoadState.NIFTY.state,'LOADED');assert.equal(state.indexLoadState.NIFTY.freshness.state,'RECORDED');assert.equal(state.loadedScope.baseline,'');assert.equal(nodes.get('load').disabled,false);assert(nodes.get('summary-source').textContent.includes('RECORDED'));assert.equal(calls.filter(x=>x.includes('/api/research/h1-replay')).length,21,'full session must load in bounded one-hour chunks');assert.equal(state.data.NIFTY.market.length,1,'chunk boundary duplicates must be removed');
const memoryVersionBeforeSameDateRefresh=state.memoryVersion;mode='nifty-fail';await sandbox.__test.load();state=sandbox.__test.getState();assert.equal(state.memoryVersion,memoryVersionBeforeSameDateRefresh,'same-date refresh must not cancel memory loading');assert.equal(state.indexLoadState.NIFTY.state,'RETAINED');assert.equal(state.indexLoadState.SENSEX.state,'LOADED');assert.equal(state.data.NIFTY.market[0].spot_ltp,24000);assert(nodes.get('source-health').innerHTML.includes('RETAINED'));
nodes.get('date').value='2026-10-07';mode='all-fail';await sandbox.__test.load();state=sandbox.__test.getState();assert.equal(Object.keys(state.data).length,0,'old data must not be relabeled a new date');assert.equal(state.indexLoadState.NIFTY.state,'UNAVAILABLE');assert.equal(state.memoryVersion,memoryVersionBeforeSameDateRefresh+1,'different-date refresh must cancel obsolete memory');assert.equal(state.busy,false);assert.equal(nodes.get('load').disabled,false);
await assert.rejects(sandbox.__test.get('auth','/auth'));assert.equal(calls.filter(x=>x==='/auth').length,1,'no authentication retry');await sandbox.__test.get('transient','/transient');assert.equal(calls.filter(x=>x==='/transient').length,2,'one transient retry');
console.log('PASS: pre/after-open isolation, opening gap, timestamp spread, prior-day references, first15 sample counts; bounded replay chunking and dedupe; RECORDED freshness; optional baseline; per-index partial failures; same-scope retained data; different-date isolation; auth no-retry; transient retry; controls unlock.');
const replacement=sandbox.__test.mergeReplayParts([{market:[{symbol:'NIFTY',minute_bucket:'2026-10-06T09:55:00Z',spot_ltp:1}]},{market:[{symbol:'NIFTY',minute_bucket:'2026-10-06T09:55:00Z',spot_ltp:2}]}],{});assert.equal(replacement.market.length,1);assert.equal(replacement.market[0].spot_ltp,2);
const realNow=Date.now;try{Date.now=()=>Date.parse('2026-10-06T10:30:00Z');nodes.get('date').value='2026-10-06';mode='success';await sandbox.__test.load();calls=[];await sandbox.__test.load();assert.equal(calls.filter(x=>x.includes('/api/research/h1-replay')).length,3,'refresh only overlap tail per index');assert(calls.every(url=>!url.includes('from=09:15')),'no whole-day re-download');}finally{Date.now=realNow;}
console.log('PASS: refreshed row replaces previous same observation; refresh only downloads overlapping tail.');
const saved=new Map();sandbox.window.localStorage={getItem:k=>saved.get(k)??null,setItem:(k,v)=>saved.set(k,v)};
sandbox.__test.restoreRefreshPreference();assert.equal(nodes.get('auto').checked,true,'auto ON for first visit');nodes.get('auto').checked=false;sandbox.__test.rememberRefreshPreference();nodes.get('auto').checked=true;sandbox.__test.restoreRefreshPreference();assert.equal(nodes.get('auto').checked,false,'explicit OFF persists');
try{Date.now=()=>Date.parse('2026-10-06T09:56:00Z');const st=sandbox.__test.getState();for(const s of ['NIFTY','SENSEX','BANKNIFTY']){st.data[s].market=[{symbol:s,minute_bucket:'2026-10-06T09:55:00Z'}];st.data[s].options=[{symbol:s,minute_bucket:'2026-10-06T09:55:00Z'}];st.data[s].chain=[{symbol:s,minute_bucket:'2026-10-06T09:55:00Z'}];}sandbox.__test.renderSourceHealth();assert(nodes.get('summary-source').textContent.startsWith('LIVE'));assert(nodes.get('pcr-source-status').textContent.includes('NIFTY: LIVE'));const graph=nodes.get('pcr-index-grid').innerHTML,oldCalls=calls.length;Date.now=()=>Date.parse('2026-10-06T10:00:00Z');sandbox.__test.renderSourceHealth();assert(nodes.get('source-health').innerHTML.includes('DELAYED'));assert(nodes.get('summary-source').textContent.startsWith('DELAYED'));assert(nodes.get('pcr-source-status').textContent.includes('NIFTY: DELAYED'));assert(nodes.get('status').textContent.includes('NIFTY DELAYED'));assert(nodes.get('coverage').textContent.includes('DELAYED'));assert.equal(nodes.get('pcr-index-grid').innerHTML,graph,'age tick preserves graph/inspector');assert.equal(calls.length,oldCalls,'age tick needs no network');}finally{Date.now=realNow;}
assert(html.includes('id="auto" type="checkbox" checked'));assert(html.includes('@media(max-width:1100px),(pointer:coarse)'));console.log('PASS: automatic refresh preference; synchronized aging labels; chart preservation and no network on age ticks.');

mode='success';nodes.get('memory-days').value='2';sandbox.__test.setRecordedDates(['2026-10-01','2026-10-05']);calls=[];
const originalFetch=sandbox.fetch;let progressiveMemory=null;
sandbox.fetch=async url=>{if(url.includes('date=2026-10-01')&&progressiveMemory===null)progressiveMemory=JSON.parse(JSON.stringify(sandbox.__test.getMemory().NIFTY));return originalFetch(url);};
await sandbox.__test.loadMemory();sandbox.fetch=originalFetch;
const memoryCalls=calls.filter(url=>url.includes('/api/research/h1-replay'));assert(memoryCalls[0].includes('date=2026-10-05'),'latest completed memory session loads first');assert.equal(progressiveMemory.sessions.length,1,'latest session must be published before older sessions finish');assert.equal(progressiveMemory.loading,true);
const loadedMemory=JSON.parse(JSON.stringify(sandbox.__test.getMemory().NIFTY));assert.equal(loadedMemory.loading,false);assert.deepEqual(loadedMemory.sessions.map(d=>d.market[0].minute_bucket.slice(0,10)),['2026-10-01','2026-10-05'],'publish history chronologically despite newest-first loading');
// All-index overview uses exact per-index expiry and the latest sampled value, including null.
const graphState=sandbox.__test.getState();for(const symbol of ['NIFTY','SENSEX','BANKNIFTY']){graphState.data[symbol]={market:[{symbol,minute_bucket:'2026-10-06T09:55:00Z',spot_ltp:24000}],chain:[{symbol,expiry:'2026-10-05',minute_bucket:'2026-10-06T09:52:00Z',full_chain_oi_pcr:9},{symbol,expiry:'2026-10-13',minute_bucket:'2026-10-06T09:52:00Z',full_chain_oi_pcr:1.123},{symbol,expiry:'2026-10-13',minute_bucket:'2026-10-06T09:55:00Z',full_chain_oi_pcr:null,band_pcr:88}],options:[]};}
sandbox.__test.renderAllIndexGraphs();let overview=nodes.get('all-index-grid').innerHTML;assert.equal((overview.match(/class="index-graph"/g)||[]).length,3);assert(overview.includes('2026-10-13'));assert(!overview.includes('88.000'));assert(!overview.includes('9.000000'));assert.equal((overview.match(/<svg/g)||[]).length,6,'each index has separate spot and PCR chart');assert.equal((overview.match(/Full PCR · ratio<strong class="annex-current">—/g)||[]).length,3,'latest null must not carry forward older PCR');
sandbox.__test.selectDashboardTab('swing');assert.equal(nodes.get('all-index-overview').hidden,true);sandbox.__test.selectDashboardTab('pcr-spot');assert.equal(nodes.get('all-index-overview').hidden,false);assert.equal(nodes.get('tab-observations').attributes['aria-selected'],'true');
// Quotes share the existing auto preference and foreground cadence, without duplicate requests.
calls=[];nodes.get('auto').checked=false;await sandbox.__test.refreshQuoteSnapshots();assert.equal(calls.length,0);nodes.get('auto').checked=true;sandbox.document.hidden=true;await sandbox.__test.refreshQuoteSnapshots();assert.equal(calls.length,0);sandbox.document.hidden=false;
try{Date.now=()=>Date.parse('2026-10-06T10:00:00Z');const pending=sandbox.__test.refreshQuoteSnapshots();await sandbox.__test.refreshQuoteSnapshots();await pending;assert.equal(calls.length,4,'one request per existing quote source');await sandbox.__test.refreshQuoteSnapshots();assert.equal(calls.length,4,'resume within 60 seconds must not refetch');Date.now=()=>Date.parse('2026-10-06T10:01:00Z');await sandbox.__test.refreshQuoteSnapshots();assert.equal(calls.length,8,'quote snapshots refresh after 60 seconds');}finally{Date.now=realNow;}
console.log('PASS: memory survives same-date refresh, date changes invalidate it, newest session loads first and is published progressively.');

});
