import test from 'node:test';
import assert from 'node:assert/strict';
import {deriveDataAnnex,deriveObservationData,deriveReadingChecklist,renderBusinessDashboardV1Html} from '../business-dashboard-v1-view.js';
const symbol='NIFTY',expiry='2026-10-13',contract=`${symbol}|${expiry}|24000|CE`,date='2026-10-08';
const at='2026-10-08T04:15:00Z',before='2026-10-08T04:12:00Z';
const option=(side:string,time:string,ltp:any)=>({symbol,expiry,strike:24000,option_type:side,minute_bucket:time,ltp,oi:100,iv:0,pdh:110,pdl:80,dte:5,bid:99,ask:101,volume:1200,quote_age_seconds:10,quote_timestamp:time});
function fixture(){return deriveObservationData({options:[option('CE',before,95),option('CE',at,100),option('PE',before,110),option('PE',at,105)],market:[{symbol,minute_bucket:before,spot_ltp:24000,future_ltp:24050,india_vix:12},{symbol,minute_bucket:at,spot_ltp:24010,future_ltp:24060,india_vix:11}],chain:[{symbol,expiry,minute_bucket:before,full_chain_oi_pcr:1},{symbol,expiry,minute_bucket:at,full_chain_oi_pcr:1.1}]});}
function model(cur:any,window='3m'){const annex=deriveDataAnnex(cur,[],[],symbol,expiry,contract,date,Date.parse('2026-10-08T05:00:00Z'));return deriveReadingChecklist(cur,annex,window,'LIVE');}
test('same exact endpoints produce only measured directional descriptions',()=>{const cur=fixture(),copy=structuredClone(cur),m=model(cur);assert.equal(m.spotFutureRelation,'Same measured direction');assert.equal(m.oppositeRelation,'Opposite measured directions');assert.equal(m.premium.find(r=>r.label==='Opposite premium ₹')?.delta,-5);assert.equal(m.premium.find(r=>r.label==='IV %')?.value,0);assert.equal(m.premium.find(r=>r.label==='DTE')?.value,5);assert.equal(m.market.find(r=>r.label==='India VIX')?.delta,-1);assert.equal(m.liquidity.find(r=>r.label==='Spread ₹')?.value,2);assert.equal(m.liquidity.find(r=>r.label==='Day cumulative volume')?.value,1200);assert.deepEqual(cur,copy);assert(!('score' in m));assert(!('candidate' in m));assert(!('eligible' in m));});
test('opposite premium never substitutes another date, expiry, strike or nearest timestamp',()=>{for(const patch of [{expiry:'2026-10-20'},{strike:24050},{minute_bucket:'2026-10-07T04:15:00Z'},{minute_bucket:'2026-10-08T04:14:59Z'}]){const cur=fixture();Object.assign(cur.options.find(r=>r.option_type==='PE'&&r.minute_bucket===at),patch);const m=model(cur);assert.equal(m.premium.find(r=>r.label==='Opposite premium ₹')?.value,null);assert.equal(m.oppositeRelation,'Change comparison unavailable');}});
test('different market endpoints are explicit, Current mode does not invent changes',()=>{const cur=fixture();for(const row of cur.market)row.minute_bucket=row.minute_bucket.replace(':00Z',':01Z');assert.equal(model(cur).spanSeconds,1);const current=model(cur,'Current');assert.equal(current.spotFutureRelation,'Change comparison unavailable');assert(current.market.every(r=>r.delta===null));assert(current.premium.every(r=>r.delta===null));const noBaseline=model(cur,'15m');assert.equal(noBaseline.oppositeRelation,'Change comparison unavailable');});
test('invalid liquidity, latest nulls and empty coverage stay unavailable',()=>{const cur=fixture(),latest=cur.options.find(r=>r.option_type==='CE'&&r.minute_bucket===at);Object.assign(latest,{ltp:null,oi:null,bid:101,ask:99,volume:null,iv:null});const m=model(cur);assert.equal(m.premium[0].value,null);assert.equal(m.liquidity.find(r=>r.label==='Spread ₹')?.value,null);assert.equal(m.liquidity.find(r=>r.label==='Day cumulative volume')?.value,null);assert.equal(m.stocks.available,0);assert.equal(m.stocks.at,null);assert.equal(model({}).optionAt,null);});
test('quote breadth exposes usable denominator and separate response time',()=>{const cur=fixture(),a=deriveDataAnnex(cur,[],[],symbol,expiry,contract,date);const m=deriveReadingChecklist(cur,a,'3m','RETAINED',{timestamp:before,stocks:[{change:1},{change:-1},{change:0},{change:null}]},{timestamp:at,sectors:[{pct:null}]});assert.deepEqual(m.stocks,{at:before,total:4,available:3,increased:1,decreased:1,flat:1});assert.equal(m.sectors.available,0);assert.equal(m.freshness,'RETAINED');});
test('browser embeds checklist helper and preserves three modes and read-only paths',()=>{const html=renderBusinessDashboardV1Html({} as any);assert(html.includes('const deriveReadingChecklist='));assert(html.includes('id="reading-checklist"'));assert(html.includes('lang="or"'));assert(html.includes('id="reading-guide"'));assert(html.includes('Previous-close quote comparisons'));assert(html.includes("$('reading-checklist').hidden=name!=='observations'"));assert(!html.includes('method:'));});

test('direction description refuses mismatched comparison endpoints',()=>{const cur=fixture(),a=deriveDataAnnex(cur,[],[],symbol,expiry,contract,date);const future=a.currentDay.find(r=>r.field==='future_ltp')!;future.current.at='2026-10-08T04:15:01Z';assert.equal(deriveReadingChecklist(cur,a).spotFutureRelation,'Different endpoint timestamps; alignment unverified');});
