import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {deriveMarketBook as book} from '../market-book-model.js';
import {renderBusinessDashboardV1Html} from '../business-dashboard-v1-view.js';
const symbol='NIFTY',expiry='2026-10-13',tradeDate='2026-10-08',recordedDates=['2026-10-05','2026-10-06','2026-10-07','2026-10-08'];
const at=(min:number,day=tradeDate)=>new Date(Date.parse(day+'T03:45:00Z')+min*60000).toISOString();
function fixture(){const market=[0,3,6,9,12,15,18].map(min=>({symbol,minute_bucket:at(min),truth_verdict:'TRUE',spot_ltp:22000+min,spot_high:22050,spot_low:21950,pdh:22015,pdl:21980,future_ltp:22010+min,india_vix:15+min/100}));const options=market.flatMap(m=>['CE','PE'].map(type=>({symbol,expiry,expiry_bucket:'CURRENT',strike:22000,option_type:type,truth_verdict:'TRUE',minute_bucket:m.minute_bucket,ltp:type==='CE'?100+(m.spot_ltp-22000):100-(m.spot_ltp-22000),iv:18,oi:1000+(m.spot_ltp-22000)*10,pdh:110,pdl:90,day_high:125,day_low:75})));const chain=market.map(m=>({symbol,expiry,minute_bucket:m.minute_bucket,truth_verdict:'TRUE',full_chain_oi_pcr:1.1,full_pcr_source:'Exact archived full-chain source',call_wall_strike:22100,call_wall_oi:1000,put_wall_strike:21900,put_wall_oi:1200}));return {market,options,chain};}
const run=(current=fixture(),extra:any={})=>book({current,symbol,tradeDate,recordedDates,window:'3m',...extra});
test('premium behaviour rejects zero levels and uses the common positioning timestamp',()=>{const c=fixture();c.options.forEach(r=>{r.pdh=0;r.pdl=0;});c.options.push({...c.options[0],strike:22200,minute_bucket:at(15),ltp:9999});const p=run(c).premiumOverview;assert.equal(p.total,2);assert.equal(p.missingLevels,2);assert.equal(p.above,0);assert.equal(p.below,0);assert.equal(p.at,at(18));assert.equal(p.rows[0].range.complete,true);});
test('notable PCR and selected-pair OI changes require verified adjacent exact records',()=>{const c=fixture();c.chain.forEach((r,i)=>r.full_chain_oi_pcr=1+i/100);const m=run(c);assert.equal(m.notableGroups.find(g=>g.category==='PCR')!.count,6);assert.equal(m.notableGroups.find(g=>g.category==='OI')!.count,12);c.chain.forEach(r=>r.full_pcr_source='Unverified');c.options=c.options.filter(r=>r.minute_bucket!==at(9));const gap=run(c);assert.equal(gap.notableGroups.find(g=>g.category==='PCR')!.count,0);assert.equal(gap.notableGroups.find(g=>g.category==='OI')!.count,8);});
test('premium notable response retains the event strike instead of the selected strike',()=>{const c=fixture();c.options.push(...c.options.filter(r=>r.option_type==='CE').map(r=>({...r,strike:22100,ltp:r.ltp+20,pdh:130})));const e=run(c).notableGroups.find(g=>g.category==='PREMIUM')!.events.find(e=>e.strike===22100&&e.kind==='Observed crossing interval');assert(e);assert.equal(e.responseStrike,22100);assert.equal(e.responses[0].sides[0].from,132);assert.equal(e.responses[0].sides[0].value,135);assert.match(e.responses[0].sides[1].state,/event premium missing/);});
test('positioning ranks only same-time recorded strikes and retains same-contract OI baselines',()=>{const c=fixture();c.options.push(...c.options.filter(r=>r.option_type==='CE').map(r=>({...r,strike:22100,oi:r.oi*2})));c.options.push({...c.options[0],strike:22200,minute_bucket:at(15),oi:999999});const p=run(c).positioning;assert.equal(p.topCalls[0].strike,22100);assert.equal(p.topCalls.length,2);assert(Math.abs(p.topCalls[0].share!-200/3)<1e-10);assert.equal(p.topCalls[0].oi.delta,60);assert(!p.changes.some(r=>r.strike===22200));assert.equal(p.at,at(18));assert.equal(p.spot,22018);assert.match(p.scope,/returned recorded strikes/);});
test('wall persistence resets at missing buckets and migration OI never compares different strikes',()=>{const c=fixture();c.chain.splice(5,1);c.chain.at(-1)!.call_wall_strike=22150;const m=run(c,{window:'15m'});assert.equal(m.callWall.oiDelta,null);assert.equal(m.positioning.callPersistence.samples,1);assert.equal(m.positioning.putPersistence.samples,1);assert.equal(m.positioning.gaps.length,1);assert.equal(m.positioning.gaps[0].minutes,6);assert.equal(m.positioning.timeline.filter(e=>e.side==='CALL').length,0);});
test('event responses require exact event contract and exact future timestamp',()=>{const c=fixture();c.chain[4].call_wall_strike=22150;const m=run(c),e=m.positioning.timeline.find(e=>e.side==='CALL'&&e.minute_bucket===at(12));assert(e);assert.equal(e.responses[0].sides[0].value,115);assert.equal(e.responses[0].sides[1].value,85);assert.match(e.responses[1].sides[0].state,/Pending/);const gap=fixture();gap.chain[4].call_wall_strike=22150;gap.options=gap.options.filter(r=>r.minute_bucket!==at(15));const missing=run(gap).positioning.timeline.find(e=>e.side==='CALL'&&e.minute_bucket===at(12));assert.equal(missing.responses[0].sides[0].value,null);assert.match(missing.responses[0].sides[0].state,/target record missing/);});
test('multi-expiry positioning keeps exact swing expiry and unknown PCR provenance excluded',()=>{const c=fixture(),prior=fixture();for(const kind of ['market','options','chain'] as const)prior[kind].forEach(r=>r.minute_bucket=r.minute_bucket.replace(tradeDate,'2026-10-07'));prior.chain.forEach(r=>r.expiry='2026-10-19');assert.equal(run(c,{history:[prior],window:'1s'}).positioning.expiryContext[0].previousCall,null);c.chain.forEach(r=>r.full_pcr_source='Unverified');assert.equal(run(c).positioning.expiryContext[0].pcr,null);});
test('neon direction requires exact synchronized spot and opposite premiums',()=>{const m=run();assert.equal(m.bias,'CE_SUPPORTING');assert.equal(m.spot.delta,3);assert.equal(m.ce.delta,3);assert.equal(m.pe.delta,-3);const c=fixture();c.options.find(r=>r.option_type==='PE'&&r.minute_bucket===at(18))!.minute_bucket=at(17);assert.equal(run(c).bias,'UNVERIFIED');const bear=fixture();bear.market.forEach(r=>r.spot_ltp=22000-(Date.parse(r.minute_bucket)-Date.parse(at(0)))/60000);bear.options.forEach(r=>r.ltp=r.option_type==='CE'?100-(Date.parse(r.minute_bucket)-Date.parse(at(0)))/60000:100+(Date.parse(r.minute_bucket)-Date.parse(at(0)))/60000);assert.equal(run(bear).bias,'PE_SUPPORTING');});
test('five-minute missing stays missing; unknown rows cannot substitute',()=>{const c=fixture();c.market.push({...c.market[0],minute_bucket:at(13),truth_verdict:'UNKNOWN',spot_ltp:999});const m=run(c,{window:'5m'});assert.equal(m.spot.from,null);assert.equal(m.bias,'UNVERIFIED');assert.equal(m.spot.value,22018);assert.equal(run(fixture(),{window:'15m'}).spot.from,22003);});
test('cross-expiry comparisons retain exact identity without directional colour',()=>{const c=fixture();c.options.push(...c.options.filter(r=>r.option_type==='PE').map(r=>({...r,expiry:'2026-10-19',ltp:r.ltp+20})));const m=run(c,{oppositeExpiry:'2026-10-19'});assert.equal(m.pe.expiry,'2026-10-19');assert.equal(m.pe.value,102);assert.equal(m.bias,'UNVERIFIED');assert.equal(m.expiryPairs.length,2);assert(m.fourthExpiryMissing);});
test('intrinsic/extrinsic uses exact same-time spot; implied IV remains separate',()=>{const m=run();assert.equal(m.ce.intrinsic,18);assert.equal(m.ce.extrinsic,100);assert.equal(m.ce.impliedIv,18);assert.equal(m.ce.open,null);const c=fixture();c.options.find(r=>r.option_type==='CE'&&r.minute_bucket===at(18))!.ltp=5;assert.equal(run(c).ce.extrinsic,null);c.market.pop();assert.equal(run(c).ce.intrinsic,null);});
test('first 15m range requires opening coverage; gaps do not create cross events',()=>{const m=run();assert(m.spot.range.complete);assert.equal(m.spot.range.high,22012);assert.equal(m.spot.range.events[0].at,at(15));const c=fixture();c.market.shift();assert.equal(run(c).spot.range.complete,false);const gap=fixture();gap.market.splice(5,1);assert.equal(run(gap).spot.range.events.length,0);});
test('pivots require exact previous session and 15:30 endpoint',()=>{const prior=fixture();prior.market=[{...prior.market[0],minute_bucket:'2026-10-07T10:00:00Z',spot_high:22100,spot_low:21900,spot_ltp:22000}];prior.options=[{...prior.options[0],minute_bucket:'2026-10-07T10:00:00Z',day_high:120,day_low:80,ltp:100}];const m=run(fixture(),{history:[prior]});assert.equal(m.spot.pivot.P,22000);assert.equal(m.spot.pivot.R3,22200);assert.equal(m.ce.pivot.S3,60);prior.market[0].minute_bucket='2026-10-07T09:57:00Z';assert.equal(run(fixture(),{history:[prior]}).spot.pivot,null);});
test('swing exact session/contract keeps missing histories missing and blocks futures rollover',()=>{const prior=fixture();for(const kind of ['market','options','chain'] as const)prior[kind].forEach(r=>r.minute_bucket=r.minute_bucket.replace(tradeDate,'2026-10-07'));const m=run(fixture(),{history:[prior],window:'1s'});assert.equal(m.spot.from,22018);assert.equal(m.spot.points.length,2);assert.equal(m.ce.points.length,2);assert.equal(m.pcr.points.length,2);assert.equal(m.future.from,null);assert.equal(m.future.pdh,null);assert.equal(m.future.pivot,null);assert.equal(m.ce.from,118);prior.options.forEach(r=>r.expiry='2026-10-06');assert.equal(run(fixture(),{history:[prior],window:'1s'}).ce.from,null);assert.equal(run(fixture(),{history:[prior],window:'3s'}).spot.from,null);});
test('full PCR provenance and wall migration do not imply same-strike OI',()=>{const c=fixture();c.chain.at(-1)!.call_wall_strike=22150;const m=run(c);assert.equal(m.callWall.delta,50);assert.equal(m.callWall.oiDelta,null);c.chain.forEach(r=>r.full_pcr_source='Source provenance unverified');assert.equal(run(c).pcr.value,null);assert.equal(run(c).pcr.delta,null);});
test('BANKNIFTY keeps actual recorded expiry identities; relative buckets are not frequency labels',()=>{const c=fixture();for(const k of ['market','options','chain'] as const)c[k].forEach(r=>r.symbol='BANKNIFTY');assert.equal(run(c,{symbol:'BANKNIFTY'}).expiries.length,1);c.options.forEach(r=>r.expiry_bucket='MONTHLY');assert.equal(run(c,{symbol:'BANKNIFTY'}).expiries.length,1);assert.equal(run().behaviour.length,2);});
test('crossing events never bracket UNKNOWN rows or wide gaps',()=>{const c=fixture();c.options.forEach(r=>{if(r.option_type==='CE'&&r.minute_bucket===at(9))r.truth_verdict='UNKNOWN';});const m=run(c);assert.equal(m.events.filter(e=>e.minute_bucket===at(12)&&e.option_type==='CE'&&e.kind==='Observed crossing interval').length,0);assert(m.events.some(e=>e.minute_bucket===at(12)&&e.option_type==='CE'&&e.kind==='First observed outside level'));});
test('serialized production book renders every chapter and preserves selections',()=>{const html=renderBusinessDashboardV1Html({} as any),scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);const nodes=new Map<string,any>();for(const id of [...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]))nodes.set(id,{value:'',innerHTML:'',textContent:'',classList:{add(){},remove(){},toggle(){}},setAttribute(){},offsetWidth:0});const ctx:any={document:{getElementById:(id:string)=>nodes.get(id)},Date,Map,Set,Number,String,Array,Object,Math};vm.createContext(ctx);vm.runInContext(scripts[0],ctx);const state={date:tradeDate,recordedDates,current:{NIFTY:fixture()},history:{},baseline:{},health:{},stocks:{},sectors:null,cash:null};ctx.api={derive:vm.runInContext('deriveMarketBook',ctx),getState:()=>state,refresh(){},memory:async()=>{}};vm.runInContext('globalThis.installed=installMarketBook(api)',ctx);assert(nodes.get('mb-page').innerHTML.includes('CE-supporting'));for(let i=1;i<13;i++){nodes.get('mb-next').onclick();assert(nodes.get('mb-page').innerHTML.includes('<h2>'));assert(!nodes.get('mb-page').innerHTML.includes('undefined'));}nodes.get('mb-window').value='5m';nodes.get('mb-window').onchange();assert(nodes.get('mb-page').innerHTML.includes('Agreement unverified'));assert.equal((html.match(/id="market-book"/g)||[]).length,1);assert(!html.includes('min-width:540px'));nodes.get('mb-window').value='3m';nodes.get('mb-window').onchange();nodes.get('mb-next').onclick();nodes.get('mb-next').onclick();assert(nodes.get('mb-page').innerHTML.includes('viewBox="0 0 480 340"'));assert(nodes.get('mb-page').innerHTML.includes('PDH'));assert(nodes.get('mb-page').innerHTML.includes('PDL'));nodes.get('mb-nav').onclick({target:{closest:()=>({dataset:{page:'6'}})}});assert(nodes.get('mb-page').innerHTML.includes('05 · Previous-session connection'));nodes.get('mb-page').onchange({target:{id:'mb-notable-filter',value:'OI'}});assert(nodes.get('mb-page').innerHTML.includes('value="OI" selected'));nodes.get('mb-nav').onclick({target:{closest:()=>({dataset:{page:'7'}})}});assert(nodes.get('mb-page').innerHTML.includes('05 · Exact-expiry comparison'));assert(nodes.get('mb-page').innerHTML.includes('mb-neon-red'));assert(nodes.get('mb-page').innerHTML.includes('mb-neon-green'));assert(html.includes('mb-neon-red 1.8s'));nodes.get('mb-page').onchange({target:{id:'mb-behaviour-filter',value:'PDL'}});assert(nodes.get('mb-page').innerHTML.includes('1 of 2 returned contracts'));assert(nodes.get('mb-page').innerHTML.includes('value="PDL" selected'));nodes.get('mb-nav').onclick({target:{closest:()=>({dataset:{page:'9'}})}});assert(nodes.get('mb-page').innerHTML.includes('viewBox="0 0 480 390"'));assert(nodes.get('mb-page').innerHTML.includes('Exact interval changes'));assert(nodes.get('mb-page').innerHTML.includes('Latest six paired'));assert(nodes.get('mb-page').innerHTML.includes('Spot ↑ / PCR →')); });

test('missing canonical wall fields never claim migration',()=>{const c=fixture();c.chain.forEach(r=>(r as any).call_wall_strike=null);const m=run(c);assert.equal(m.callWall.strike,null);assert.equal(m.callWall.oiDelta,null);assert.equal(m.callWall.reason,'Wall strike unavailable');assert.equal(m.positioning.callPersistence.samples,0);});

test('premium neon is contract-specific: below PDL red and recovery green',()=>{const c=fixture();const ce=c.options.filter(r=>r.option_type==='CE');ce.forEach((r,i)=>r.ltp=[100,95,88,85,91,95,99][i]);const m=run(c);assert.equal(m.ce.levelBehaviour.tone,'GREEN');assert.equal(m.ce.levelBehaviour.state,'PDL recovered');assert.equal(m.ce.levelBehaviour.since,at(12));assert.equal(m.pe.levelBehaviour.tone,'RED');assert.equal(m.pe.levelBehaviour.state,'Below PDL');assert.equal(m.premiumOverview.rows.find(r=>r.type==='CE')!.levelBehaviour.tone,'GREEN');ce.at(-1)!.ltp=89;assert.equal(run(c).ce.levelBehaviour.tone,'RED');});
test('PDH touch is green; rejection needs two exact lower samples and persists below PDH',()=>{const c=fixture();const ce=c.options.filter(r=>r.option_type==='CE');ce.forEach((r,i)=>r.ltp=[100,110,108,105,106,104,103][i]);const m=run(c);assert.equal(m.ce.levelBehaviour.tone,'RED');assert.match(m.ce.levelBehaviour.state,/2 lower samples/);assert.equal(m.ce.levelBehaviour.since,at(9));const touch=fixture();touch.options.filter(r=>r.option_type==='CE').at(-1)!.ltp=110;assert.equal(run(touch).ce.levelBehaviour.state,'At PDH');assert.equal(run(touch).ce.levelBehaviour.tone,'GREEN');c.options=c.options.filter(r=>Date.parse(r.minute_bucket)<=Date.parse(at(6)));assert.equal(run(c).ce.levelBehaviour.tone,'NEUTRAL');});
test('gaps, changed levels and UNKNOWN quotes never fabricate premium recovery or rejection',()=>{for(const mode of ['gap','level','unknown']){const c=fixture();const ce=c.options.filter(r=>r.option_type==='CE');ce.forEach((r,i)=>r.ltp=i<5?85:95);if(mode==='gap')c.options=c.options.filter(r=>r.option_type!=='CE'||r.minute_bucket!==at(12));if(mode==='level')ce.at(-1)!.pdl=92;if(mode==='unknown')ce[4].truth_verdict='UNKNOWN';assert.equal(run(c).ce.levelBehaviour.tone,'NEUTRAL',mode);}const invalid=fixture();invalid.options.forEach(r=>{r.pdh=0;r.pdl=0;});assert.equal(run(invalid).ce.levelBehaviour.tone,'NEUTRAL');invalid.options.forEach(r=>{r.pdh=80;r.pdl=90;});assert.match(run(invalid).ce.levelBehaviour.state,/invalid/);});
test('PDH rejection never migrates between expiry or strike identities',()=>{const c=fixture();c.options.push(...c.options.filter(r=>r.option_type==='CE').map((r,i)=>({...r,expiry:'2026-10-19',ltp:[100,110,108,105,106,104,103][i]})));const m=run(c);assert.equal(m.ce.levelBehaviour.tone,'GREEN');assert.equal(m.expiryPairs[1].ce.levelBehaviour.tone,'RED');});

test('spot-PCR relation requires matching exact current and baseline times',()=>{const c=fixture();c.chain.forEach((r,i)=>r.full_chain_oi_pcr=1+i/100);const p=run(c).spotPcr;assert.equal(p.ready,true);assert.equal(p.state,'Spot ↑ / PCR ↑');assert.equal(p.windows.find(r=>r.minutes===5)!.state,'Unverified');assert.equal(p.windows.find(r=>r.minutes===15)!.spotDelta,15);assert.equal(p.timeline[0].spotDelta,3);c.chain.pop();assert.equal(run(c).spotPcr.ready,false);assert.equal(run(c).spotPcr.at,null);assert.equal(run(c).spotPcr.windows[0].state,'Unverified');});
test('paired changes never bridge missing PCR provenance or recorder gaps',()=>{const c=fixture();c.chain.forEach((r,i)=>r.full_chain_oi_pcr=1+i/100);c.chain[5].full_pcr_source='Unverified';let p=run(c).spotPcr;assert.equal(p.ready,false);assert.equal(p.timeline[0].pcrDelta,null);assert.equal(p.timeline[0].state,'Unverified');c.chain.splice(5,1);p=run(c).spotPcr;assert.equal(p.timeline[0].spotDelta,null);assert.equal(p.timeline[0].pcrDelta,null);});
test('prior-session PCR context and swing comparison retain exact expiry',()=>{const prior=fixture();for(const kind of ['market','options','chain'] as const)prior[kind].forEach(r=>r.minute_bucket=r.minute_bucket.replace(tradeDate,'2026-10-07'));prior.chain.forEach(r=>r.full_chain_oi_pcr=.9);const p=run(fixture(),{history:[prior],window:'1s'}).spotPcr;assert.equal(p.priorPcr.value,.9);assert.equal(p.ready,true);prior.chain.forEach(r=>r.expiry='2026-10-19');assert.equal(run(fixture(),{history:[prior],window:'1s'}).spotPcr.ready,false);assert.equal(run(fixture(),{history:[prior]}).spotPcr.priorPcr.value,null);});

test('participation snapshots keep missing quotes separate, rank actual percentages and preserve filters',()=>{
 const html=renderBusinessDashboardV1Html({} as any),script=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1];
 const nodes=new Map<string,any>();for(const id of [...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]))nodes.set(id,{value:'',innerHTML:'',textContent:'',classList:{add(){},remove(){},toggle(){}},setAttribute(){},offsetWidth:0});
 const ctx:any={document:{getElementById:(id:string)=>nodes.get(id)},Date,Map,Set,Number,String,Array,Object,Math};vm.createContext(ctx);vm.runInContext(script,ctx);
 const state:any={date:tradeDate,recordedDates,current:{NIFTY:fixture()},history:{},baseline:{},health:{},stocks:{NIFTY:{timestamp:'2026-10-09T03:45:00Z',stocks:[{name:'Negative',change:-2,price:100},{name:'Positive',change:1,price:200},{name:'Flat',change:0,price:300},{name:'Missing',change:null},{name:'Boolean',change:false},{name:'Whitespace',change:' '},{name:'Invalid',change:NaN},{name:'<unsafe>',change:3,price:400}]}},sectors:{timestamp:'2026-10-09T03:45:00Z',sectors:[{name:'Nifty PSU Bank',pct:1},{name:'Nifty Midcap 100',pct:-1},{name:'Nifty IT',pct:0},{name:'Other <index>',pct:null}]}};
 ctx.api={derive:vm.runInContext('deriveMarketBook',ctx),getState:()=>state,refresh(){},memory:async()=>{}};vm.runInContext('globalThis.installed=installMarketBook(api)',ctx);
 nodes.get('mb-nav').onclick({target:{closest:()=>({dataset:{page:'8'}})}});
 let page=nodes.get('mb-page').innerHTML;assert.match(page,/2 up, 1 down, 1 flat, 4 missing of 8 returned quotes/);assert.match(page,/4\/8 returned quotes have a usable %/);assert(page.indexOf('&lt;unsafe&gt;')<page.indexOf('Positive'));assert(!page.includes('<unsafe>'));assert(page.includes('-2%'));assert(page.includes('Separate snapshot date 2026-10-09; selected replay 2026-10-08'));assert(page.includes('Financials · PSU Bank'));assert(page.includes('Broader market · index proxies'));assert(page.includes('Other &lt;index&gt;'));assert(page.includes('selected 3m replay window does not apply'));assert(!page.includes('TRUE recorded data only'));
 nodes.get('mb-page').onchange({target:{id:'mb-participation-filter',value:'MISSING'}});page=nodes.get('mb-page').innerHTML;assert(page.includes('value="MISSING" selected'));assert(!page.includes('class="mb-rank-name">Positive'));assert(page.includes('class="mb-rank-name">Boolean'));
 vm.runInContext('installed.render()',ctx);assert(nodes.get('mb-page').innerHTML.includes('value="MISSING" selected'));
 state.stocks={};state.sectors=null;state.quoteStatus={NIFTY:'Authentication required; open the app and check your session.',sectors:'Timed out after retry'};vm.runInContext('installed.render()',ctx);page=nodes.get('mb-page').innerHTML;assert(page.includes('Unavailable · no quote observations returned.'));assert(!page.includes('<strong>0</strong>'));assert(!page.includes('0/0 returned quotes'));assert(!page.includes('undefined'));assert(!page.includes('NaN'));assert(page.includes('Authentication required'));assert(page.includes('Timed out after retry'));state.stocks={NIFTY:{stocks:[{name:'No change',change:0,price:100}]}};nodes.get('mb-page').onchange({target:{id:'mb-participation-filter',value:'ALL'}});page=nodes.get('mb-page').innerHTML;assert(page.includes('<strong>1</strong>Flat'));assert(page.includes('class="mb-value ">0%</strong>'));state.stocks.NIFTY.stocks=[{name:'Missing quote',change:null}];vm.runInContext('installed.render()',ctx);page=nodes.get('mb-page').innerHTML;assert(page.includes('<strong>—</strong>Up'));assert(page.includes('<strong>1</strong>Missing'));assert(!page.includes('<strong>0</strong>'));
});
