import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {deriveMarketBook as book} from '../market-book-model.js';
import {renderBusinessDashboardV1Html} from '../business-dashboard-v1-view.js';
const symbol='NIFTY',expiry='2026-10-13',tradeDate='2026-10-08',recordedDates=['2026-10-05','2026-10-06','2026-10-07','2026-10-08'];
const at=(min:number,day=tradeDate)=>new Date(Date.parse(day+'T03:45:00Z')+min*60000).toISOString();
function fixture(){const market=[0,3,6,9,12,15,18].map(min=>({symbol,minute_bucket:at(min),truth_verdict:'TRUE',spot_ltp:22000+min,spot_high:22050,spot_low:21950,pdh:22015,pdl:21980,future_ltp:22010+min,india_vix:15+min/100}));const options=market.flatMap(m=>['CE','PE'].map(type=>({symbol,expiry,expiry_bucket:'CURRENT',strike:22000,option_type:type,truth_verdict:'TRUE',minute_bucket:m.minute_bucket,ltp:type==='CE'?100+(m.spot_ltp-22000):100-(m.spot_ltp-22000),iv:18,oi:1000+(m.spot_ltp-22000)*10,pdh:110,pdl:90,day_high:125,day_low:75})));const chain=market.map(m=>({symbol,expiry,minute_bucket:m.minute_bucket,truth_verdict:'TRUE',full_chain_oi_pcr:1.1,full_pcr_source:'Exact archived full-chain source',call_wall_strike:22100,call_wall_oi:1000,put_wall_strike:21900,put_wall_oi:1200}));return {market,options,chain};}
const run=(current=fixture(),extra:any={})=>book({current,symbol,tradeDate,recordedDates,window:'3m',...extra});
test('positioning ranks only same-time recorded strikes and retains same-contract OI baselines',()=>{const c=fixture();c.options.push(...c.options.filter(r=>r.option_type==='CE').map(r=>({...r,strike:22100,oi:r.oi*2})));c.options.push({...c.options[0],strike:22200,minute_bucket:at(15),oi:999999});const p=run(c).positioning;assert.equal(p.topCalls[0].strike,22100);assert.equal(p.topCalls.length,2);assert(Math.abs(p.topCalls[0].share!-200/3)<1e-10);assert.equal(p.topCalls[0].oi.delta,60);assert(!p.changes.some(r=>r.strike===22200));assert.equal(p.at,at(18));assert.equal(p.spot,22018);assert.match(p.scope,/returned recorded strikes/);});
test('wall persistence resets at missing buckets and migration OI never compares different strikes',()=>{const c=fixture();c.chain.splice(5,1);c.chain.at(-1)!.call_wall_strike=22150;const m=run(c,{window:'15m'});assert.equal(m.callWall.oiDelta,null);assert.equal(m.positioning.callPersistence.samples,1);assert.equal(m.positioning.putPersistence.samples,1);assert.equal(m.positioning.gaps.length,1);assert.equal(m.positioning.gaps[0].minutes,6);assert.equal(m.positioning.timeline.filter(e=>e.side==='CALL').length,0);});
test('event responses require exact event contract and exact future timestamp',()=>{const c=fixture();c.chain[4].call_wall_strike=22150;const m=run(c),e=m.positioning.timeline.find(e=>e.side==='CALL'&&e.minute_bucket===at(12));assert(e);assert.equal(e.responses[0].sides[0].value,115);assert.equal(e.responses[0].sides[1].value,85);assert.match(e.responses[1].sides[0].state,/Pending/);const gap=fixture();gap.chain[4].call_wall_strike=22150;gap.options=gap.options.filter(r=>r.minute_bucket!==at(15));const missing=run(gap).positioning.timeline.find(e=>e.side==='CALL'&&e.minute_bucket===at(12));assert.equal(missing.responses[0].sides[0].value,null);assert.match(missing.responses[0].sides[0].state,/target record missing/);});
test('multi-expiry positioning keeps exact swing expiry and unknown PCR provenance excluded',()=>{const c=fixture(),prior=fixture();for(const kind of ['market','options','chain'] as const)prior[kind].forEach(r=>r.minute_bucket=r.minute_bucket.replace(tradeDate,'2026-10-07'));prior.chain.forEach(r=>r.expiry='2026-10-19');assert.equal(run(c,{history:[prior],window:'1s'}).positioning.expiryContext[0].previousCall,null);c.chain.forEach(r=>r.full_pcr_source='Unverified');assert.equal(run(c).positioning.expiryContext[0].pcr,null);});
test('neon direction requires exact synchronized spot and opposite premiums',()=>{const m=run();assert.equal(m.bias,'CE_SUPPORTING');assert.equal(m.spot.delta,3);assert.equal(m.ce.delta,3);assert.equal(m.pe.delta,-3);const c=fixture();c.options.find(r=>r.option_type==='PE'&&r.minute_bucket===at(18))!.minute_bucket=at(17);assert.equal(run(c).bias,'UNVERIFIED');const bear=fixture();bear.market.forEach(r=>r.spot_ltp=22000-(Date.parse(r.minute_bucket)-Date.parse(at(0)))/60000);bear.options.forEach(r=>r.ltp=r.option_type==='CE'?100-(Date.parse(r.minute_bucket)-Date.parse(at(0)))/60000:100+(Date.parse(r.minute_bucket)-Date.parse(at(0)))/60000);assert.equal(run(bear).bias,'PE_SUPPORTING');});
test('five-minute missing stays missing; unknown rows cannot substitute',()=>{const c=fixture();c.market.push({...c.market[0],minute_bucket:at(13),truth_verdict:'UNKNOWN',spot_ltp:999});const m=run(c,{window:'5m'});assert.equal(m.spot.from,null);assert.equal(m.bias,'UNVERIFIED');assert.equal(m.spot.value,22018);assert.equal(run(fixture(),{window:'15m'}).spot.from,22003);});
test('cross-expiry comparisons retain exact identity without directional colour',()=>{const c=fixture();c.options.push(...c.options.filter(r=>r.option_type==='PE').map(r=>({...r,expiry:'2026-10-19',ltp:r.ltp+20})));const m=run(c,{oppositeExpiry:'2026-10-19'});assert.equal(m.pe.expiry,'2026-10-19');assert.equal(m.pe.value,102);assert.equal(m.bias,'UNVERIFIED');assert.equal(m.expiryPairs.length,2);assert(m.fourthExpiryMissing);});
test('intrinsic/extrinsic uses exact same-time spot; implied IV remains separate',()=>{const m=run();assert.equal(m.ce.intrinsic,18);assert.equal(m.ce.extrinsic,100);assert.equal(m.ce.impliedIv,18);assert.equal(m.ce.open,null);const c=fixture();c.options.find(r=>r.option_type==='CE'&&r.minute_bucket===at(18))!.ltp=5;assert.equal(run(c).ce.extrinsic,null);c.market.pop();assert.equal(run(c).ce.intrinsic,null);});
test('first 15m range requires opening coverage; gaps do not create cross events',()=>{const m=run();assert(m.spot.range.complete);assert.equal(m.spot.range.high,22012);assert.equal(m.spot.range.events[0].at,at(15));const c=fixture();c.market.shift();assert.equal(run(c).spot.range.complete,false);const gap=fixture();gap.market.splice(5,1);assert.equal(run(gap).spot.range.events.length,0);});
test('pivots require exact previous session and 15:30 endpoint',()=>{const prior=fixture();prior.market=[{...prior.market[0],minute_bucket:'2026-10-07T10:00:00Z',spot_high:22100,spot_low:21900,spot_ltp:22000}];prior.options=[{...prior.options[0],minute_bucket:'2026-10-07T10:00:00Z',day_high:120,day_low:80,ltp:100}];const m=run(fixture(),{history:[prior]});assert.equal(m.spot.pivot.P,22000);assert.equal(m.spot.pivot.R3,22200);assert.equal(m.ce.pivot.S3,60);prior.market[0].minute_bucket='2026-10-07T09:57:00Z';assert.equal(run(fixture(),{history:[prior]}).spot.pivot,null);});
test('swing exact session/contract keeps missing histories missing and blocks futures rollover',()=>{const prior=fixture();for(const kind of ['market','options','chain'] as const)prior[kind].forEach(r=>r.minute_bucket=r.minute_bucket.replace(tradeDate,'2026-10-07'));const m=run(fixture(),{history:[prior],window:'1s'});assert.equal(m.spot.from,22018);assert.equal(m.spot.points.length,2);assert.equal(m.ce.points.length,2);assert.equal(m.pcr.points.length,2);assert.equal(m.future.from,null);assert.equal(m.future.pdh,null);assert.equal(m.future.pivot,null);assert.equal(m.ce.from,118);prior.options.forEach(r=>r.expiry='2026-10-06');assert.equal(run(fixture(),{history:[prior],window:'1s'}).ce.from,null);assert.equal(run(fixture(),{history:[prior],window:'3s'}).spot.from,null);});
test('full PCR provenance and wall migration do not imply same-strike OI',()=>{const c=fixture();c.chain.at(-1)!.call_wall_strike=22150;const m=run(c);assert.equal(m.callWall.delta,50);assert.equal(m.callWall.oiDelta,null);c.chain.forEach(r=>r.full_pcr_source='Source provenance unverified');assert.equal(run(c).pcr.value,null);assert.equal(run(c).pcr.delta,null);});
test('BANKNIFTY keeps actual recorded expiry identities; relative buckets are not frequency labels',()=>{const c=fixture();for(const k of ['market','options','chain'] as const)c[k].forEach(r=>r.symbol='BANKNIFTY');assert.equal(run(c,{symbol:'BANKNIFTY'}).expiries.length,1);c.options.forEach(r=>r.expiry_bucket='MONTHLY');assert.equal(run(c,{symbol:'BANKNIFTY'}).expiries.length,1);assert.equal(run().behaviour.length,2);});
test('crossing events never bracket UNKNOWN rows or wide gaps',()=>{const c=fixture();c.options.forEach(r=>{if(r.option_type==='CE'&&r.minute_bucket===at(9))r.truth_verdict='UNKNOWN';});const m=run(c);assert.equal(m.events.filter(e=>e.minute_bucket===at(12)&&e.option_type==='CE'&&e.kind==='Observed crossing interval').length,0);assert(m.events.some(e=>e.minute_bucket===at(12)&&e.option_type==='CE'&&e.kind==='First observed outside level'));});
test('serialized production book renders every chapter and preserves selections',()=>{const html=renderBusinessDashboardV1Html({} as any),scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);const nodes=new Map<string,any>();for(const id of [...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]))nodes.set(id,{value:'',innerHTML:'',textContent:'',classList:{add(){},remove(){},toggle(){}},setAttribute(){},offsetWidth:0});const ctx:any={document:{getElementById:(id:string)=>nodes.get(id)},Date,Map,Set,Number,String,Array,Object,Math};vm.createContext(ctx);vm.runInContext(scripts[0],ctx);const state={date:tradeDate,recordedDates,current:{NIFTY:fixture()},history:{},baseline:{},health:{},stocks:{},sectors:null,cash:null};ctx.api={derive:vm.runInContext('deriveMarketBook',ctx),getState:()=>state,refresh(){},memory:async()=>{}};vm.runInContext('globalThis.installed=installMarketBook(api)',ctx);assert(nodes.get('mb-page').innerHTML.includes('CE-supporting'));for(let i=1;i<13;i++){nodes.get('mb-next').onclick();assert(nodes.get('mb-page').innerHTML.includes('<h2>'));assert(!nodes.get('mb-page').innerHTML.includes('undefined'));}nodes.get('mb-window').value='5m';nodes.get('mb-window').onchange();assert(nodes.get('mb-page').innerHTML.includes('Agreement unverified'));assert.equal((html.match(/id="market-book"/g)||[]).length,1);assert(!html.includes('min-width:540px'));nodes.get('mb-window').value='3m';nodes.get('mb-window').onchange();nodes.get('mb-next').onclick();nodes.get('mb-next').onclick();assert(nodes.get('mb-page').innerHTML.includes('viewBox="0 0 480 340"'));assert(nodes.get('mb-page').innerHTML.includes('PDH'));assert(nodes.get('mb-page').innerHTML.includes('PDL')); });

test('missing canonical wall fields never claim migration',()=>{const c=fixture();c.chain.forEach(r=>(r as any).call_wall_strike=null);const m=run(c);assert.equal(m.callWall.strike,null);assert.equal(m.callWall.oiDelta,null);assert.equal(m.callWall.reason,'Wall strike unavailable');assert.equal(m.positioning.callPersistence.samples,0);});
