import test from "node:test";
import assert from "node:assert/strict";
import { validateOptionBuyerRegimeLift } from "../option-buyer-regime-lift-validation.js";
import type { MdiInput, MdiSourceQualityMap } from "../mdi-research-shadow.js";

const verified:MdiSourceQualityMap={PCR:"VERIFIED",WALL:"VERIFIED",IV:"VERIFIED",VIX:"VERIFIED",FUTURES:"VERIFIED"};
function mdi(bull=true):MdiInput{return {previous:{ts:"2026-09-03T04:00:00.000Z",sourceQuality:verified,fullPcr:.8,band7Pcr:.8,callWallStrike:24000,putWallStrike:23800,callWallStrength:100,putWallStrength:100,ceIv:12,peIv:12,indiaVix:12,futureLtp:23900},current:{ts:"2026-09-03T04:03:00.000Z",sourceQuality:verified,fullPcr:bull?1:.6,band7Pcr:bull?1:.6,callWallStrike:bull?24050:23950,putWallStrike:bull?23850:23750,callWallStrength:bull?85:120,putWallStrength:bull?120:85,ceIv:bull?15:11,peIv:bull?11:15,indiaVix:bull?11.5:12.5,futureLtp:bull?24020:23820},strikeStep:50};}
const candidate=(side:"CE"|"PE",dte=1)=>({symbol:"NIFTY" as const,side,strike:23900,expiryDate:"2026-09-03",dte,moneyness:"ATM" as const,premiumLtp:100,capitalFit:true,liquidityOk:true,spreadOk:true,premiumResponseConfirmed:true,deltaGammaResponseConfirmed:true,thetaIvBurdenAcceptable:true,multiExpiryConflictAbsent:true,currentOrNearExpiryUsable:true,higherDteUsable:false,fallbackDteApproved:true});
const payoff=(exitBid:number)=>({exchange:"NSE" as const,quantity:130,accountState:"NON_DEBIT" as const,evaluationDate:"2026-09-03",entry:{bid:99,ask:100,quality:"VERIFIED" as const},exit:{bid:exitBid,ask:exitBid+.5,quality:"VERIFIED" as const}});
const regime=(kind:"UP"|"DOWN"|"RANGE"|"HIGH"|"TRANSITION"|"UNKNOWN")=>kind==="UP"?{trendDirection:"UP" as const,rangeState:"NORMAL" as const,volatilityState:"NORMAL" as const,transitionDetected:false,evidenceCount:4,minEvidenceCount:3}:kind==="DOWN"?{trendDirection:"DOWN" as const,rangeState:"NORMAL" as const,volatilityState:"NORMAL" as const,transitionDetected:false,evidenceCount:4,minEvidenceCount:3}:kind==="RANGE"?{trendDirection:"FLAT" as const,rangeState:"COMPRESSED" as const,volatilityState:"LOW" as const,transitionDetected:false,evidenceCount:4,minEvidenceCount:3}:kind==="HIGH"?{trendDirection:"UP" as const,rangeState:"EXPANDING" as const,volatilityState:"HIGH" as const,transitionDetected:false,evidenceCount:4,minEvidenceCount:3}:kind==="TRANSITION"?{trendDirection:"FLAT" as const,rangeState:"NORMAL" as const,volatilityState:"NORMAL" as const,transitionDetected:true,evidenceCount:4,minEvidenceCount:3}:{trendDirection:"UNAVAILABLE" as const,rangeState:"UNAVAILABLE" as const,volatilityState:"UNAVAILABLE" as const,transitionDetected:null,evidenceCount:1,minEvidenceCount:3};
const sample=(id:string,bull:boolean,side:"CE"|"PE",dte:number,exitBid:number,r:ReturnType<typeof regime>)=>({sampleId:id,mdiInput:mdi(bull),candidate:candidate(side,dte),payoffContract:{side,strike:23900,expiryDate:"2026-09-03"},netPayoffInput:payoff(exitBid),regimeInput:r});

test("splits option buyer MDI lift by deterministic market regime",()=>{const out=validateOptionBuyerRegimeLift([sample("a",true,"CE",1,115,regime("UP")),sample("b",false,"CE",1,95,regime("UP")),sample("c",true,"CE",3,110,regime("RANGE"))]);assert.equal(out.state,"USABLE");assert.equal(out.regimeQualifiedSamples,3);const up=out.regimes.find(x=>x.regime==="TRENDING_UP");assert.equal(up?.baselineCount,2);assert.equal(up?.mdiFilteredCount,1);assert.ok((up?.avgNetReturnLiftPctPoints??0)>0);assert.equal(out.regimePolicy,"MARKET_REGIME_ENGINE_V1_VALIDATED_EVIDENCE_ONLY");assert.equal(out.aggregationPolicy,"COUNT_WEIGHTED_FROM_DTE_BUCKET_SUMMARIES");});

test("unknown regime is excluded without fabricating a label",()=>{const out=validateOptionBuyerRegimeLift([sample("a",true,"CE",1,110,regime("UNKNOWN")),sample("b",true,"CE",1,110,regime("UP"))]);assert.equal(out.unknownRegimeSamples,1);assert.equal(out.regimeQualifiedSamples,1);});

test("duplicate sample id fails closed",()=>{const s=sample("x",true,"CE",1,110,regime("UP"));const out=validateOptionBuyerRegimeLift([s,s]);assert.equal(out.state,"UNAVAILABLE");assert.ok(out.blockers.includes("DUPLICATE_SAMPLE_ID"));});

test("no regime-qualified samples fails closed",()=>{const out=validateOptionBuyerRegimeLift([sample("x",true,"CE",1,110,regime("UNKNOWN"))]);assert.equal(out.state,"UNAVAILABLE");assert.ok(out.blockers.includes("NO_REGIME_QUALIFIED_OPTION_BUYER_SAMPLES"));});

test("research layer has zero live authority and no significance claim",()=>{const out=validateOptionBuyerRegimeLift([]);assert.equal(out.inferencePolicy,"DESCRIPTIVE_ONLY_NO_STATISTICAL_SIGNIFICANCE_CLAIM");assert.equal(out.affectsVerdict,false);assert.equal(out.affectsTelegram,false);assert.equal(out.affectsExecution,false);assert.equal(out.createsOrders,false);assert.equal(out.aiMayOverride,false);});
