export function renderH1TheoryDashboardHtml(): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OptionPilot Pro · Date-wise Theory Lab</title>
<style>
:root{color-scheme:dark;--bg:#050814;--panel:#0b1324;--line:#203253;--text:#eef6ff;--muted:#8ba0c0;--cyan:#3cecff;--green:#58f0ac;--red:#ff7890;--amber:#ffd166;--violet:#bb9cff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 10% 0,rgba(60,236,255,.1),transparent 28%),var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}.shell{max-width:1400px;margin:auto;padding:18px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.brand{font-weight:900}.tag,.pill{border:1px solid var(--line);border-radius:999px;padding:6px 9px;font-size:10px;font-weight:800}.tag{color:var(--cyan)}h1{font-size:clamp(24px,4vw,42px);margin:22px 0 8px}.sub{color:var(--muted);max-width:900px;line-height:1.5}.filters{display:grid;grid-template-columns:1.2fr 1fr 1fr 1fr auto;gap:9px;margin:18px 0;background:var(--panel);border:1px solid var(--line);padding:12px;border-radius:16px}select,input,button{width:100%;border:1px solid var(--line);background:#091223;color:var(--text);border-radius:10px;padding:10px;font-weight:700}button{cursor:pointer;background:linear-gradient(90deg,#11334a,#1b2852);color:var(--cyan)}.status{margin:10px 0;color:var(--muted);font-size:12px}.summary,.grid{display:grid;gap:10px}.summary{grid-template-columns:repeat(4,1fr)}.card,.event{background:linear-gradient(160deg,#0c172a,#08111f);border:1px solid var(--line);border-radius:15px;padding:13px}.label{font-size:9px;color:var(--muted);letter-spacing:.08em;font-weight:850}.value{font-size:20px;font-weight:900;margin-top:5px}.grid{grid-template-columns:repeat(4,1fr);margin-top:10px}.metric{display:flex;justify-content:space-between;gap:8px;border-top:1px solid #182945;padding-top:7px;margin-top:7px;font-size:11px}.metric span{color:var(--muted)}.good{color:var(--green)}.bad{color:var(--red)}.warn{color:var(--amber)}.events{margin-top:12px}.event{margin-top:8px}.event-top{display:flex;justify-content:space-between;gap:8px;font-weight:850}.evidence{font-size:11px;color:var(--muted);margin-top:8px;line-height:1.55}.empty{padding:22px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:14px}.safety{margin-top:14px;border:1px solid rgba(60,236,255,.25);border-radius:13px;padding:12px;color:var(--muted);font-size:11px}@media(max-width:850px){.filters{grid-template-columns:1fr 1fr}.summary,.grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.shell{padding:11px}.filters,.summary,.grid{grid-template-columns:1fr}}
</style></head><body><main class="shell"><div class="top"><div class="brand">OPTIONPILOT PRO</div><span class="tag">DATE-WISE THEORY LAB</span></div><h1>Recorded-Day Evidence Filter</h1><div class="sub">NIFTY → SENSEX → BANKNIFTY. Applies 3m clue, 6m confirmation, 15m transition validation and 30m sustained-regime windows to verified H1 database records.</div>
<section class="filters"><select id="date"></select><select id="symbol"><option>NIFTY</option><option>SENSEX</option><option>BANKNIFTY</option></select><input id="from" type="time" value="09:15" min="09:15" max="15:30"><input id="to" type="time" value="15:30" min="09:15" max="15:30"><button id="run">Analyze day</button></section><div id="status" class="status">Loading recorded dates…</div><div id="result"></div>
<div class="safety"><b>RESEARCH ONLY · PRODUCTION IMPACT: NONE.</b> UNKNOWN is never neutral. Results cannot alter live verdict, Telegram, candidate selection or execution. Every direction is a descriptive hypothesis until forward/walk-forward validation.</div></main>
<script>
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=2)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'—';
const tone=v=>v==='BULLISH'?'good':v==='BEARISH'?'bad':v==='BALANCED'?'warn':'';
let rows=[];
function syncDates(){const symbol=document.querySelector('#symbol').value;const dates=[...new Set(rows.filter(r=>r.symbol===symbol).map(r=>r.tradeDate))];const el=document.querySelector('#date');el.innerHTML=dates.map(d=>'<option>'+esc(d)+'</option>').join('');if(!dates.length)el.innerHTML='<option value="">No verified dates</option>';}
async function loadDates(){const res=await fetch('/api/research/h1-theory-dates');const data=await res.json();rows=data.dates||[];syncDates();document.querySelector('#status').textContent=data.ok?rows.length+' verified date/index records available':(data.reason||'Date index unavailable');if(data.ok&&rows.length)run();}
function metric(k,v){return '<div class="metric"><span>'+esc(k)+'</span><b>'+esc(v)+'</b></div>'}
function render(data){const q=data.dataQuality||{};const windows=data.latestWindows||[];const events=data.transitions||[];document.querySelector('#result').innerHTML='<section class="summary"><div class="card"><div class="label">DAY VERDICT</div><div class="value '+tone(data.dayVerdict)+'">'+esc(data.dayVerdict)+'</div></div><div class="card"><div class="label">MARKET MINUTES</div><div class="value">'+esc(q.marketMinutes)+'</div></div><div class="card"><div class="label">TRUTH MARKERS</div><div class="value">'+esc(q.markerCount)+'</div></div><div class="card"><div class="label">COVERAGE</div><div class="value">'+esc(q.coverageStatus)+'</div></div></section><section class="grid">'+windows.map(w=>'<article class="card"><div class="label">'+esc(w.windowMinutes)+'M · '+esc(w.stage)+'</div><div class="value '+tone(w.direction)+'">'+esc(w.direction)+'</div>'+metric('Spot Δ',n(w.spotChangePct,3)+'%')+metric('Futures Δ',n(w.futureChangePct,3)+'%')+metric('Futures OI Δ',w.futureOiChange)+metric('PCR Δ',n(w.pcrChange,3))+metric('CE / PE Δ',n(w.cePremiumChangePct)+'% / '+n(w.pePremiumChangePct)+'%')+metric('Call / Put wall shift',w.callWallShift+' / '+w.putWallShift)+metric('ATM IV Δ',n(w.atmIvChange,3))+metric('Evidence',w.status)+'</article>').join('')+'</section><section class="events"><h3>Detected transition hypotheses ('+events.length+')</h3>'+(events.length?events.map(e=>'<article class="event"><div class="event-top"><span>'+esc(new Date(e.timestamp).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'}))+' · <b class="'+tone(e.direction)+'">'+esc(e.direction)+'</b></span><span class="pill">'+esc(e.responseEfficiency)+'</span></div><div class="evidence">Prior: '+esc(e.priorDirection)+' · '+e.evidence.map(esc).join(' · ')+'<br>Label: '+esc(e.label)+'</div></article>').join(''):'<div class="empty">No aligned 3m→6m→15m direction-change hypothesis was found in the verified rows.</div>')+'</section>';
const cas=data.cas||{};const cm=cas.metrics||{};const casHtml='<section class="events"><h3>Closing Auction Scanner · Proxy v1</h3><article class="event"><div class="event-top"><span class="'+tone(cas.direction)+'">'+esc(cas.state||'UNAVAILABLE')+' · '+esc(cas.direction||'UNAVAILABLE')+'</span><span class="pill">PROXY ONLY</span></div><div class="grid"><div>'+metric('Evidence',cas.evidenceStatus)+metric('Baseline samples',cas.baselineSamples)+metric('Closing samples',cas.closingSamples)+metric('Next-session risk map',cas.nextSessionRiskMap)+'</div><div>'+metric('Spot / Futures Δ',n(cm.spotChangePct,3)+'% / '+n(cm.futureChangePct,3)+'%')+metric('Futures OI Δ',cm.futureOiChange)+metric('PCR Δ',n(cm.pcrChange,3))+metric('Response efficiency',cm.responseEfficiency)+'</div><div>'+metric('CE / PE premium Δ',n(cm.cePremiumChangePct)+'% / '+n(cm.pePremiumChangePct)+'%')+metric('ATM IV Δ',n(cm.atmIvChange,3))+metric('Wall shifts',cm.callWallShift+' / '+cm.putWallShift)+'</div><div>'+metric('Baseline rel. spread',n(cm.baselineRelativeSpread,4))+metric('Closing rel. spread',n(cm.closingRelativeSpread,4))+metric('Spread expansion',n(cm.spreadExpansionRatio,2)+'x')+metric('Threshold',cas.thresholdLabel)+'</div></div><div class="evidence"><b>Inference:</b> '+esc((cas.inferred||[]).join(' '))+'<br><b>Full-CAS gaps:</b> '+esc((cas.missing||[]).join(', '))+'<br>This is a next-session review flag, not a prediction or trade signal.</div></article></section>';
document.querySelector('.summary')?.insertAdjacentHTML('afterend',casHtml);
}
async function run(){const date=document.querySelector('#date').value;if(!date)return;const p=new URLSearchParams({date,symbol:document.querySelector('#symbol').value,from:document.querySelector('#from').value,to:document.querySelector('#to').value,scope:'CORE'});document.querySelector('#status').textContent='Analyzing verified database rows…';const res=await fetch('/api/research/h1-theory-analysis?'+p);const data=await res.json();document.querySelector('#status').textContent=data.ok?'Analysis ready · read-only':(data.reason||'Analysis unavailable');render(data);}
document.querySelector('#symbol').addEventListener('change',()=>{syncDates();run()});document.querySelector('#run').addEventListener('click',run);loadDates();
</script></body></html>`;
}
