import { deriveMdiResearchShadow, type MdiInput, type MdiResult } from "./mdi-research-shadow.js";

export type SwingMdiBias = "BULLISH_PERSISTENCE" | "BEARISH_PERSISTENCE" | "TRANSITION_UP" | "TRANSITION_DOWN" | "NEUTRAL" | "UNAVAILABLE";
export interface SwingMdiSessionInput { tradeDate: string; mdiInput: MdiInput; }
export interface SwingMdiWindow { sessions: 3 | 5 | 20; availableSessions: number; usableSessions: number; coveragePct: number; averageMdi: number | null; slopePerSession: number | null; positivePct: number | null; negativePct: number | null; persistencePct: number | null; bias: SwingMdiBias; reasons: string[]; }
export interface SwingMdiResearchResult { latestTradeDate: string | null; windows: SwingMdiWindow[]; latestMdi: number | null; latestMdiBias: MdiResult["bias"]; ruleVersion: "SWING_MDI_RESEARCH_V1"; semantics: "MULTI_DAY_RESEARCH_ONLY"; sourcePolicy: "FULLY_VERIFIED_DAILY_MDI_ONLY"; affectsVerdict: false; affectsTelegram: false; affectsExecution: false; createsOrders: false; aiMayOverride: false; }
const round1=(v:number)=>Math.round(v*10)/10;
function validDate(v:string){ if(!/^\d{4}-\d{2}-\d{2}$/.test(v)) return false; const d=new Date(`${v}T00:00:00Z`); return Number.isFinite(d.getTime()) && d.toISOString().slice(0,10)===v; }
function tsDate(v:string){ const ms=Date.parse(v); return Number.isFinite(ms)?new Date(ms).toISOString().slice(0,10):null; }
function sessionBound(s:SwingMdiSessionInput){ return tsDate(s.mdiInput.previous.ts)===s.tradeDate && tsDate(s.mdiInput.current.ts)===s.tradeDate; }
function deriveSession(s:SwingMdiSessionInput){ if(!validDate(s.tradeDate)||!sessionBound(s)) return null; return {tradeDate:s.tradeDate,result:deriveMdiResearchShadow(s.mdiInput)}; }
function fullyVerifiedResult(result:MdiResult){ return result.mdi!=null && result.bias!=="UNAVAILABLE" && result.coveragePct===100 && result.sourcePolicy==="VERIFIED_COMPONENT_SOURCES_ONLY"; }
function linearSlope(points:Array<{x:number;y:number}>){ if(points.length<2)return null; const n=points.length,xm=points.reduce((s,p)=>s+p.x,0)/n,ym=points.reduce((s,p)=>s+p.y,0)/n; let num=0,den=0; for(const p of points){num+=(p.x-xm)*(p.y-ym);den+=(p.x-xm)**2;} return den===0?null:round1(num/den); }
function classify(values:number[],slope:number|null){ if(values.length<2)return {bias:"UNAVAILABLE" as SwingMdiBias,persistencePct:null,reasons:["At least two fully verified MDI sessions are required."]}; const pos=values.filter(v=>v>=25).length,neg=values.filter(v=>v<=-25).length,p=round1(Math.max(pos,neg)/values.length*100),first=values[0],last=values.at(-1)!; if(first<0&&last>=25&&(slope??0)>0)return {bias:"TRANSITION_UP" as SwingMdiBias,persistencePct:p,reasons:["Fully verified MDI transitioned upward with positive slope."]}; if(first>0&&last<=-25&&(slope??0)<0)return {bias:"TRANSITION_DOWN" as SwingMdiBias,persistencePct:p,reasons:["Fully verified MDI transitioned downward with negative slope."]}; if(pos/values.length>=.6&&last>=25)return {bias:"BULLISH_PERSISTENCE" as SwingMdiBias,persistencePct:p,reasons:["At least 60% of usable sessions are bullish and latest remains bullish."]}; if(neg/values.length>=.6&&last<=-25)return {bias:"BEARISH_PERSISTENCE" as SwingMdiBias,persistencePct:p,reasons:["At least 60% of usable sessions are bearish and latest remains bearish."]}; return {bias:"NEUTRAL" as SwingMdiBias,persistencePct:p,reasons:["No persistent or transition-grade structure."]}; }
function buildWindow(derived:Array<{tradeDate:string;result:MdiResult}>,sessions:3|5|20):SwingMdiWindow{ const slice=derived.slice(-sessions); const usable=slice.map((x,i)=>({x:i,result:x.result})).filter(x=>fullyVerifiedResult(x.result)); const values=usable.map(x=>x.result.mdi as number),coveragePct=slice.length?round1(values.length/slice.length*100):0; const slope=linearSlope(usable.map(x=>({x:x.x,y:x.result.mdi as number}))),base=classify(values,slope),reasons=[...base.reasons]; if(slice.length<sessions)reasons.push(`Only ${slice.length} of ${sessions} requested sessions are available.`); if(values.length<slice.length)reasons.push(`${slice.length-values.length} session(s) excluded because daily MDI was unavailable or below 100% verified component coverage.`); let bias=base.bias,persistencePct=base.persistencePct; if(slice.length<2||coveragePct<80){bias="UNAVAILABLE";persistencePct=null;reasons.push(`Usable coverage ${coveragePct}% is below 80%; fail closed.`);} return {sessions,availableSessions:slice.length,usableSessions:values.length,coveragePct,averageMdi:values.length?round1(values.reduce((a,b)=>a+b,0)/values.length):null,slopePerSession:slope,positivePct:values.length?round1(values.filter(v=>v>=25).length/values.length*100):null,negativePct:values.length?round1(values.filter(v=>v<=-25).length/values.length*100):null,persistencePct,bias,reasons}; }
export function deriveSwingMdiResearch(inputs:SwingMdiSessionInput[]):SwingMdiResearchResult{ const byDate=new Map<string,SwingMdiSessionInput>(); const conflicted=new Set<string>(); for(const input of inputs){ if(!validDate(input.tradeDate)||!sessionBound(input))continue; const existing=byDate.get(input.tradeDate); if(!existing&&!conflicted.has(input.tradeDate))byDate.set(input.tradeDate,input); else if(existing){ const a=deriveMdiResearchShadow(existing.mdiInput),b=deriveMdiResearchShadow(input.mdiInput); if(a.mdi!==b.mdi||a.bias!==b.bias||a.coveragePct!==b.coveragePct){byDate.delete(input.tradeDate);conflicted.add(input.tradeDate);} } } const ordered=[...byDate.values()].sort((a,b)=>a.tradeDate.localeCompare(b.tradeDate)); const derived=ordered.map(deriveSession).filter((x):x is {tradeDate:string;result:MdiResult}=>x!==null); const latest=derived.at(-1)??null; const latestUsable=latest&&fullyVerifiedResult(latest.result)?latest:null; return {latestTradeDate:latestUsable?.tradeDate??null,windows:([3,5,20] as const).map(s=>buildWindow(derived,s)),latestMdi:latestUsable?.result.mdi??null,latestMdiBias:latestUsable?.result.bias??"UNAVAILABLE",ruleVersion:"SWING_MDI_RESEARCH_V1",semantics:"MULTI_DAY_RESEARCH_ONLY",sourcePolicy:"FULLY_VERIFIED_DAILY_MDI_ONLY",affectsVerdict:false,affectsTelegram:false,affectsExecution:false,createsOrders:false,aiMayOverride:false}; }
